source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'metapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for metapp

  pod 'RxSwift', '~> 3.0.0'
  pod 'RxCocoa', '~> 3.0.0'
  pod 'RxDataSources', '~> 1.0.0'
  pod 'SnapKit', '~> 3.0'
  pod 'Swinject', '2.0.0-beta.2'
  pod 'SwinjectStoryboard', '1.0.0-beta.2'
  #pod 'AsyncSwift', :git => 'https://github.com/duemunk/Async'
  pod 'Carpaccio', :git => 'https://github.com/MrZoidberg/Carpaccio', :branch => 'master' 
  pod 'XCGLogger', '~> 4.0.0'
  pod 'RealmSwift'

  target 'metappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'metappUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
